name 'webserver'
maintainer 'Alan Voiski'
maintainer_email 'avoiski@avenuecode.com'
license 'all_rights'
description 'Installs/Configures webserver'
long_description 'Installs/Configures webserver'
version '0.1.0'
